services:
  db:
    image: postgres:latest
    container_name: money-tracker
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret"
